scalaVersion := "2.12.18"
name := "hello-spark"
organization := "cc.phish3y.hello-spark"
version := "1.0"

libraryDependencies += "org.scala-lang.modules" %% "scala-parser-combinators" % "2.3.0"
libraryDependencies += "org.apache.spark" %% "spark-core" % "3.5.5"
libraryDependencies += "org.apache.spark" %% "spark-sql" % "3.5.5"
// libraryDependencies += "org.apache.spark" %% "spark-sql-kafka-0-10" % "3.5.5"
// libraryDependencies += "org.apache.spark" %% "spark-token-provider-kafka-0-10" % "3.5.5"
// libraryDependencies += "org.apache.kafka" % "kafka-clients" % "3.5.2"
