---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: spark-extra-jars
spec:
  storageClassName: ""
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /home/phish3y/spark-app/jars