apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: spark-extra-jars
  namespace: default
spec:
  storageClassName: "" 
  resources:
    requests:
      storage: 10Gi
  accessModes:
    - ReadWriteOnce
