apiVersion: sparkoperator.k8s.io/v1beta2
kind: SparkApplication
metadata:
  name: hello-spark
  namespace: default
spec:
  type: Scala
  mode: cluster
  image: spark:3.5.5
  mainClass: HelloSpark
  mainApplicationFile: local:///tmp/jars/hello-spark_2.12-1.0.jar
  driver:
    cores: 1
    memory: 1G
    labels:
      version: 3.5.5
    serviceAccount: spark-operator-spark
    env:
      - name: AWS_JAVA_V1_DISABLE_DEPRECATION_ANNOUNCEMENT
        value: "true"
      - name: AWS_ACCESS_KEY_ID
        valueFrom:
          secretKeyRef:
            name: spark-apps
            key: aws-access-key-id
      - name: AWS_SECRET_ACCESS_KEY
        valueFrom:
          secretKeyRef:
            name: spark-apps
            key: aws-secret-access-key
    volumeMounts:
      - name: extra-jars
        mountPath: /tmp/jars
  executor:
    cores: 2
    instances: 4
    memory: 2G
    labels:
      version: 3.5.5
    serviceAccount: spark-operator-spark
    env:
      - name: AWS_JAVA_V1_DISABLE_DEPRECATION_ANNOUNCEMENT
        value: "true"
      - name: AWS_ACCESS_KEY_ID
        valueFrom:
          secretKeyRef:
            name: spark-apps
            key: aws-access-key-id
      - name: AWS_SECRET_ACCESS_KEY
        valueFrom:
          secretKeyRef:
            name: spark-apps
            key: aws-secret-access-key
    volumeMounts:
      - name: extra-jars
        mountPath: /tmp/jars
  deps:
    jars:
      - local:///tmp/jars/hadoop-common-3.3.4.jar
      - local:///tmp/jars/hadoop-aws-3.3.4.jar
      - local:///tmp/jars/aws-java-sdk-bundle-1.12.782.jar
  volumes:
    - name: extra-jars
      persistentVolumeClaim:
        claimName: spark-extra-jars