name: image
on:
  push:
    branches:
      - 'main'
permissions: 
  contents: read
  packages: write 
jobs:
  push:
    runs-on: ubuntu-latest
    steps:
      - name: setup-buildx
        uses: docker/setup-buildx-action@v2
      - name: registry-login
        uses: docker/login-action@v2 
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/checkout@v3
      - name: build
        id: build
        uses: docker/build-push-action@v3
        with:
          context: .
          file: Dockerfile
          push: true
          build-args: |
          tags: |
            ghcr.io/spark3.5.5-custom:${{ github.sha }}